2020-09-20 13:08:53,638 - GlobalLog.py [line:125] - ERROR: this is a logger error message
2020-09-20 13:08:53,638 - GlobalLog.py [line:126] - CRITICAL: this is a logger critical message
2020-09-20 13:10:34 | ERROR | 这是一个Error问题 
2020-09-20 13:11:01 | ERROR | 这是一个Error问题 
2020-09-20 13:11:19 | ERROR | 这是一个Error问题 
2020-09-20 13:12:22,954 - Dir_Tools.py [line:78] - ERROR: [WinError 3] 系统找不到指定的路径。: 'E:\\WorkSpace\\PycharmProjects\\UiAutomationFramework\\Utils'
2020-09-20 13:12:49,638 - Dir_Tools.py [line:78] - ERROR: [WinError 3] 系统找不到指定的路径。: 'E:\\WorkSpace\\PycharmProjects\\UiAutomationFramework\\Utils'
2020-09-20 13:13:16,555 - Dir_Tools.py [line:78] - ERROR: [WinError 3] 系统找不到指定的路径。: 'E:\\WorkSpace\\PycharmProjects\\UiAutomationFramework\\Utils'
2020-09-20 13:14:01,124 - Dir_Tools.py [line:103] - ERROR: [Errno 2] No such file or directory: 'E:\\WorkSpace\\PycharmProjects\\UiAutomationFramework\\Utils\\copy\\aaaa.gzip'
2020-09-20 13:14:57,951 - Dir_Tools.py [line:103] - ERROR: [Errno 2] No such file or directory: 'E:\\WorkSpace\\PycharmProjects\\UiAutomationFramework\\Utils\\copy\\aaaa.gzip'
2020-09-20 13:16:01,718 - Dir_Tools.py [line:88] - ERROR: [Errno 2] No such file or directory: 'E:\\WorkSpace\\PycharmProjects\\UiAutomationFramework\\Utils\\copy'
2020-09-20 13:16:11,702 - Dir_Tools.py [line:88] - ERROR: [Errno 2] No such file or directory: 'E:\\WorkSpace\\PycharmProjects\\UiAutomationFramework\\Utils'
2020-09-20 13:16:28,417 - Dir_Tools.py [line:88] - ERROR: [Errno 13] Permission denied: 'D:\\Work_Spaces\\PyCharm_Project\\UiAutomationFramework\\Utils'
2020-09-20 13:17:11,980 - Dir_Tools.py [line:88] - ERROR: [Errno 2] No such file or directory: 'D:\\Work_Spaces\\PyCharm_Project\\UiAutomationFramework\\Utils\\copy\\aaaa.zip'
2020-09-20 13:18:12,926 - Dir_Tools.py [line:60] - ERROR: [WinError 3] 系统找不到指定的路径。: 'E:\\WorkSpace\\PycharmProjects\\UiAutomationFramework\\Utils'
2020-09-20 13:18:29,333 - Dir_Tools.py [line:60] - ERROR: [WinError 3] 系统找不到指定的路径。: 'E:\\WorkSpace\\PycharmProjects\\UiAutomationFramework\\Utils'
2020-09-20 13:31:31,595 - Dir_Tools.py [line:84] - ERROR: 'str' object has no attribute 'decode'
2020-09-20 13:32:43,411 - Dir_Tools.py [line:82] - ERROR: module 'os' has no attribute 'sep0'
2020-09-20 13:32:49,617 - Dir_Tools.py [line:82] - ERROR: name '_iterateExeZipFile' is not defined
2020-09-20 13:34:02,616 - Dir_Tools.py [line:82] - ERROR: name '_iterateExeZipFile' is not defined
2020-09-20 13:35:57,856 - Dir_Tools.py [line:81] - ERROR: module 'zipfile' has no attribute 'write'
2020-09-20 13:36:23,980 - Dir_Tools.py [line:82] - ERROR: module 'zipfile' has no attribute 'write'
2020-09-20 13:36:39,559 - Dir_Tools.py [line:81] - ERROR: module 'zipfile' has no attribute 'write'
2020-09-20 13:37:38,027 - Dir_Tools.py [line:85] - ERROR: module 'zipfile' has no attribute 'write'
2020-09-20 13:41:49,651 - Dir_Tools.py [line:88] - ERROR: module 'zipfile' has no attribute 'write'
2020-09-20 13:42:10,998 - Dir_Tools.py [line:86] - ERROR: module 'zipfile' has no attribute 'write'
2020-09-20 13:45:31,984 - Dir_Tools.py [line:90] - ERROR: module 'zipfile' has no attribute 'write'
2020-09-20 13:45:51,281 - Dir_Tools.py [line:88] - ERROR: module 'zipfile' has no attribute 'write'
2020-09-20 13:46:01,528 - Dir_Tools.py [line:88] - ERROR: module 'zipfile' has no attribute 'write'
2020-09-20 13:46:06,224 - Dir_Tools.py [line:88] - ERROR: 'str' object has no attribute 'compress_type'
2020-09-20 13:48:42,799 - Dir_Tools.py [line:75] - ERROR: [Errno 2] No such file or directory: ''
2020-09-20 13:48:53,871 - Dir_Tools.py [line:75] - ERROR: [Errno 2] No such file or directory: ''
2020-09-20 13:56:56,703 - Dir_Tools.py [line:73] - ERROR: list indices must be integers or slices, not str
2020-09-20 14:12:02,149 - Dir_Tools.py [line:174] - ERROR: 请检查filepath是否正确！
2020-09-20 14:18:02,973 - Dir_Tools.py [line:174] - ERROR: 请检查filepath是否正确！
2020-09-20 14:18:50,968 - Dir_Tools.py [line:178] - ERROR: aa
2020-09-20 14:19:37,854 - Dir_Tools.py [line:178] - ERROR: aa
2020-09-20 14:28:51,196 - Dir_Tools.py [line:185] - ERROR: D:\Work_Spaces\PyCharm_Project\UiAutomationFramework\Utils\AA已存在，跳过创建！
2020-09-20 14:29:35,724 - Dir_Tools.py [line:185] - ERROR: D:\Work_Spaces\PyCharm_Project\UiAutomationFramework\Utils\AA已存在，跳过创建！
