2020-12-10 09:26:49,037 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5920/wd/hub/session -> http://127.0.0.1:5920/wd/hub/session/925432d5-1d73-441a-928e-c63812e95fc7
2020-12-10 09:26:49,037 - Appium.py [line:50] - INFO: <appium.webdriver.webdriver.WebDriver (session="925432d5-1d73-441a-928e-c63812e95fc7")>
2020-12-10 09:26:56,728 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5925/wd/hub/session -> http://127.0.0.1:5925/wd/hub/session/532c1b9d-e62f-4d91-ad41-281218efc01b
2020-12-10 09:26:56,728 - Appium.py [line:50] - INFO: <appium.webdriver.webdriver.WebDriver (session="532c1b9d-e62f-4d91-ad41-281218efc01b")>
2020-12-10 09:28:20,129 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5920/wd/hub/session -> http://127.0.0.1:5920/wd/hub/session/90df5b4c-705a-40a8-a3ad-32df35c8d4ea
2020-12-10 09:28:48,950 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5920/wd/hub/session -> http://127.0.0.1:5920/wd/hub/session/1102cb9e-e8db-4f4c-b589-98365f8d1241
2020-12-10 09:29:18,915 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5920/wd/hub/session -> http://127.0.0.1:5920/wd/hub/session/4dec5425-2d48-43a6-9889-382da499de23
2020-12-10 09:29:32,040 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5925/wd/hub/session -> http://127.0.0.1:5925/wd/hub/session/3f2d19cb-7e5c-484e-bde3-53603700b286
2020-12-10 09:36:28,002 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5920/wd/hub/session -> http://127.0.0.1:5920/wd/hub/session/999d617e-feea-4aec-adc8-6691ef3d6053
2020-12-10 09:36:35,025 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5925/wd/hub/session -> http://127.0.0.1:5925/wd/hub/session/4fc7da33-c872-462e-b314-69760cc2535c
2020-12-10 09:42:47,755 - AppiumTools.py [line:54] - ERROR: 端口-5925被占用，请手动重启！
2020-12-10 09:42:55,521 - AppiumTools.py [line:54] - ERROR: 端口-5925被占用，请手动重启！
2020-12-10 09:43:40,642 - AppiumTools.py [line:50] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5926}
2020-12-10 09:44:19,574 - remote_connection.py [line:117] - INFO: Could not connect to port 5920 on host 127.0.0.1
2020-12-10 09:44:19,574 - remote_connection.py [line:136] - INFO: Could not get IP address for host: 127.0.0.1
2020-12-10 09:44:21,616 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CD37262EF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 09:44:23,647 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CD37291080>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 09:44:25,679 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CD37291198>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 09:44:40,970 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5926/wd/hub/session -> http://127.0.0.1:5926/wd/hub/session/33f50887-62f5-4919-9362-0aca02d61d0d
2020-12-10 09:45:20,927 - AppiumTools.py [line:50] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5928}
2020-12-10 09:46:41,613 - AppiumTools.py [line:54] - ERROR: 端口-5928被占用，请手动重启！
2020-12-10 09:48:02,104 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5926/wd/hub/session -> http://127.0.0.1:5926/wd/hub/session/e1eb0558-57f1-4edb-aeb3-f3de504aed76
2020-12-10 09:49:24,596 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5926/wd/hub/session -> http://127.0.0.1:5926/wd/hub/session/8f5128f6-fde5-4ddd-9237-4c25ffb07744
2020-12-10 09:50:37,343 - AppiumTools.py [line:50] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5930}
2020-12-10 09:50:45,399 - AppiumTools.py [line:50] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5930}
2020-12-10 09:51:37,161 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5926/wd/hub/session -> http://127.0.0.1:5926/wd/hub/session/1bfc41ab-033b-48d0-8a7c-7bb7dcd5c066
2020-12-10 09:52:37,917 - AppiumTools.py [line:50] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5930}
2020-12-10 09:53:30,871 - AppiumTools.py [line:54] - ERROR: 端口-5930被占用，请手动重启！
2020-12-10 09:53:42,785 - AppiumTools.py [line:29] - INFO: 捕捉到Node进程：['node.exe                     14116 Console                    2    106,004 K\n', 'node.exe                      9976 Console                    2     94,396 K\n', 'node.exe                      9800 Console                    2    115,500 K\n']
2020-12-10 09:53:42,785 - AppiumTools.py [line:54] - ERROR: 端口-5930被占用，请手动重启！
2020-12-10 09:53:47,389 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 09:53:49,428 - AppiumTools.py [line:50] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5930}
2020-12-10 09:54:34,134 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5930/wd/hub/session -> http://127.0.0.1:5930/wd/hub/session/600174ca-b17e-4d28-8d05-5bb79fcf6226
2020-12-10 09:56:07,003 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5930/wd/hub/session -> http://127.0.0.1:5930/wd/hub/session/95a3be8b-f745-446d-a4b7-6bc0b24db9f0
2020-12-10 09:57:16,756 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 09:57:23,818 - AppiumTools.py [line:51] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5930}
2020-12-10 09:57:36,057 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5930/wd/hub/session -> http://127.0.0.1:5930/wd/hub/session/f3e2c4fb-a475-4eb5-801c-998127bdabea
2020-12-10 09:59:52,021 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5930/wd/hub/session -> http://127.0.0.1:5930/wd/hub/session/6729b7a6-b3d9-4b99-9b28-341eccecc5d7
2020-12-10 10:07:09,159 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5930/wd/hub/session -> http://127.0.0.1:5930/wd/hub/session/a71d9712-cacc-419a-9008-d062e2269cdf
2020-12-10 10:08:13,448 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 10:08:18,361 - remote_connection.py [line:117] - INFO: Could not connect to port 5930 on host 127.0.0.1
2020-12-10 10:08:18,361 - remote_connection.py [line:136] - INFO: Could not get IP address for host: 127.0.0.1
2020-12-10 10:08:20,394 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7808C9048>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 10:08:20,503 - AppiumTools.py [line:51] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5930}
2020-12-10 10:08:22,421 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7808C9160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 10:08:32,258 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5930/wd/hub/session -> http://127.0.0.1:5930/wd/hub/session/d4d60e13-14d9-485c-92e1-6f2fe08fc07a
2020-12-10 10:13:16,959 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5930/wd/hub/session -> http://127.0.0.1:5930/wd/hub/session/c407ce1d-4398-4d13-bb6d-7f4353685611
2020-12-10 10:18:41,244 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 10:18:48,304 - AppiumTools.py [line:51] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5930}
2020-12-10 10:19:34,424 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5930/wd/hub/session -> http://127.0.0.1:5930/wd/hub/session/ec5143ca-b5bd-4063-9d83-4d56d8ee389b
2020-12-10 10:21:08,237 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5930/wd/hub/session -> http://127.0.0.1:5930/wd/hub/session/da633286-fdd0-42b7-aafb-4c10a3cd58ec
2020-12-10 10:22:22,057 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5930/wd/hub/session -> http://127.0.0.1:5930/wd/hub/session/3646e535-8b01-40f5-b9bf-e7df60364aa7
2020-12-10 10:19:02,301 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5930/wd/hub/session -> http://127.0.0.1:5930/wd/hub/session/bf44d346-0702-4c37-a891-7c4ca409a89f
2020-12-10 10:58:08,430 - AppiumTools.py [line:29] - INFO: 捕捉到Node进程：['node.exe                     12544 Console                    2     94,104 K\n']
2020-12-10 10:58:13,432 - AppiumTools.py [line:55] - ERROR: 端口-5930被占用，请手动重启！
2020-12-10 10:58:19,127 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 10:58:24,127 - AppiumTools.py [line:55] - ERROR: 端口-5930被占用，请手动重启！
2020-12-10 10:58:42,578 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 10:58:42,578 - AppiumTools.py [line:52] - ERROR: 端口-5930被占用，请手动重启！
2020-12-10 10:58:45,943 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 10:58:45,943 - AppiumTools.py [line:52] - ERROR: 端口-5930被占用，请手动重启！
2020-12-10 11:01:04,759 - remote_connection.py [line:117] - INFO: Could not connect to port 5930 on host 127.0.0.1
2020-12-10 11:01:04,759 - remote_connection.py [line:136] - INFO: Could not get IP address for host: 127.0.0.1
2020-12-10 11:01:06,796 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023F72E80F98>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 11:01:08,845 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023F72E9A0B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 11:01:10,885 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023F72E9A278>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 11:21:22,050 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 11:21:22,050 - AppiumTools.py [line:52] - ERROR: 端口-5930被占用，请手动重启！
2020-12-10 11:23:11,707 - Appium.py [line:284] - INFO: <appium.webdriver.webelement.WebElement (session="c9780f26-9d7b-4f1d-b7aa-82aeb7355ef6", element="82536fe7-fc6e-420e-bab0-a223b11b79ab")>
2020-12-10 11:23:46,962 - Appium.py [line:284] - INFO: com.tencent.now:id/nr
2020-12-10 11:25:09,864 - Appium.py [line:135] - ERROR: 按id查找元素失败！ 
2020-12-10 11:26:04,319 - Appium.py [line:136] - ERROR: 按id查找元素失败！ 
2020-12-10 11:57:27,930 - remote_connection.py [line:117] - INFO: Could not connect to port 5930 on host 127.0.0.1
2020-12-10 11:57:27,930 - remote_connection.py [line:136] - INFO: Could not get IP address for host: 127.0.0.1
2020-12-10 11:57:29,985 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B98108B2B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 11:57:32,012 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B98108B390>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 11:57:34,047 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B98108B518>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 11:59:35,796 - remote_connection.py [line:117] - INFO: Could not connect to port 5920 on host 127.0.0.1
2020-12-10 11:59:35,796 - remote_connection.py [line:136] - INFO: Could not get IP address for host: 127.0.0.1
2020-12-10 11:59:37,829 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016C71CD9400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 11:59:39,870 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016C71CD94E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 11:59:41,891 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016C71CD9668>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 12:00:33,274 - Appium.py [line:129] - ERROR: 按id查找元素失败！ 
2020-12-10 12:02:15,020 - Appium.py [line:129] - ERROR: 按id查找元素失败！ 
2020-12-10 12:19:29,827 - Appium.py [line:129] - ERROR: 按id查找元素失败！ 
2020-12-10 12:20:50,375 - Appium.py [line:129] - ERROR: 按id查找元素失败！ 
2020-12-10 12:38:24,135 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 12:38:26,139 - AppiumTools.py [line:48] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5930}
2020-12-10 12:38:42,253 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 12:38:44,258 - AppiumTools.py [line:48] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5926}
2020-12-10 13:50:57,543 - AppiumTools.py [line:29] - INFO: 捕捉到Node进程：['node.exe                     14992 Console                    2    101,276 K\n']
2020-12-10 13:50:57,543 - AppiumTools.py [line:52] - ERROR: 端口-5926被占用，请手动重启！
2020-12-10 13:54:06,816 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 13:54:11,754 - AppiumTools.py [line:52] - ERROR: 端口-5926被占用，请手动重启！
2020-12-10 13:54:15,212 - AppiumTools.py [line:52] - ERROR: 端口-5926被占用，请手动重启！
2020-12-10 13:54:26,514 - AppiumTools.py [line:48] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5920}
2020-12-10 13:59:41,642 - AppiumTools.py [line:29] - INFO: 捕捉到Node进程：['node.exe                     16380 Console                    2     95,836 K\n']
2020-12-10 13:59:41,644 - AppiumTools.py [line:52] - ERROR: 端口-5920被占用，请手动重启！
2020-12-10 13:59:49,663 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 13:59:57,842 - AppiumTools.py [line:48] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5920}
2020-12-10 14:05:51,485 - AppiumTools.py [line:29] - INFO: 捕捉到Node进程：['node.exe                      7940 Console                    2    118,056 K\n']
2020-12-10 14:05:58,113 - AppiumTools.py [line:48] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5920}
2020-12-10 15:07:58,720 - AppiumTools.py [line:48] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5920}
2020-12-10 15:06:40,485 - AppiumTools.py [line:48] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5920}
2020-12-10 15:08:25,866 - AppiumTools.py [line:48] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5920}
2020-12-10 15:09:59,872 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 15:10:06,933 - AppiumTools.py [line:48] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5920}
2020-12-10 15:10:36,765 - poolmanager.py [line:375] - INFO: Redirecting http://127.0.0.1:5920/wd/hub/session -> http://127.0.0.1:5920/wd/hub/session/0d82e0b4-773d-4ede-8a25-556638936c4c
2020-12-10 20:16:42,720 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 20:16:49,785 - AppiumTools.py [line:48] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5920}
2020-12-10 20:32:07,528 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 20:32:12,541 - AppiumTools.py [line:52] - ERROR: 端口-5920被占用，请手动重启！
2020-12-10 20:32:18,002 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 20:32:25,051 - AppiumTools.py [line:48] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5920}
2020-12-10 20:33:28,498 - AppiumTools.py [line:32] - INFO: 暂时没有启动过Node相关服务
2020-12-10 20:33:30,540 - AppiumTools.py [line:48] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5920}
2020-12-10 22:02:37,700 - remote_connection.py [line:117] - INFO: Could not connect to port 5920 on host 127.0.0.1
2020-12-10 22:02:37,702 - remote_connection.py [line:136] - INFO: Could not get IP address for host: 127.0.0.1
2020-12-10 22:02:39,716 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D20F2ACFD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 22:02:41,732 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D20F2D9128>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 22:02:43,755 - connectionpool.py [line:752] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D20F2D9160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
2020-12-10 22:10:27,565 - AppiumTools.py [line:48] - INFO: 正在启动Appium服务{IP：127.0.0.1,Port：5920}
